# site settings
title: Kieran Malloy
subtitle: by HTML5 UP
email: kieranmalloy123@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: kieranmalloy.com
author: Kieran Malloy
street_address: 33 Newton Street
city: Greenock
zip_code: PA16 8SB
state:
country: Scotland
phone: (+44) 7575691119

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/Kieran-M
googleplus_url: https://plus.google.com/u/0/+KieranMalloy
instagram_url: https://instagram.com/kieran_malloy
linkedin_url: https://www.linkedin.com/in/kieran-malloy-848449173
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kieran_malloy

# build settings
markdown: kramdown

sass:
style: compressed
