
title: Kieran 
subtitle: Malloy
email: kieran@kieranmalloy.com

description: >- 
  Welcome to my website
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.kieranmalloy.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Kieran Malloy
street_address: 33 Newton Street
city: Greenock
state: 
zip_code: PA16 8SB
country: Scotland
phone: (+44) 7575691119

tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

500px_url:
facebook_url:
github_url: https://github.com/u/Kieran-M
gitlab_url: https://gitlab.com/Kieran-M
googleplus_url: https://plus.google.com/u/0/+KieranMalloy
instagram_url: https://instagram.com/kieran_malloy
linkedin_url: https://www.linkedin.com/in/kieran-malloy-848449173
pinterest_url:
slack_url: 
twitter_url: https://twitter.com/Kieran_V3

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
